CREATE TABLE users (
	zpid varchar PRIMARY KEY,
	accessible_smoke_detector boolean, 
	bathroom_has_grab_bars boolean,
	wide_doors boolean,
	zestimatecost integer,
	accessible_entry boolean,
	door_has_a_knock_or_bell_signaller boolean,
	bathroom_is_reinforced_for_grab_bars boolean,
	automatic_entry boolean,
	latitude numeric NOT NULL,
	longitude numeric NOT NULL,
	doors_have_lever_handles numeric boolean,
	zip_code integer,
	tty_or_amplified_phone boolean,
	bathroom_has_raised_toilets boolean,
	bedrooms boolean,
	strobe_fire_alarm boolean,
	accessible_laundry_facility boolean,
	bathroom_has_a_roll_in_shower boolean,
	city_name varchar,
	accessible_carbon_monoxide_detector boolean,
	door_has_an_accessible_peephole boolean,
	bathroom_vanities_minimum_knee_space_27 boolean,
	kitchen_counter_minimum_knee_space_27 boolean,
	bathroom_has_lowered_toilets boolean,
	bathroom_has_a_t_turn_or_60_turning_circle boolean,
	unit_on_first_floor boolean,
	street_address varchar
);
